### ISSUE TITLE
erzwungener zeilenumbruch bei eingebetteten bildern

### ISSUE THREAD

**Issue by verymilan** [Linux-statt-Windows/nodebb-theme-persona#12]
bisher nur in der signatur getestet:
![unbenannt](https://cloud.githubusercontent.com/assets/10698140/11078573/096a543a-8807-11e5-8c6c-8b4f18b474af.png)

**Comment by rbeer** [comment]
Markiert als "enhancement", weil markdown eigentlich keine inline images vorsieht

**Comment by rbeer** [comment]
62dcced
Signaturbilder bekommen class `img-signature` mit `display: inline`

**Comment by verymilan** [comment]
> Markiert als "enhancement", weil markdown eigentlich keine inline images vorsieht

Das wundert mich: andere, Markdown nutzende Dienste haben keine Probleme damit...an dieser Stelle sicherheitshalber noch ein Auszug aus der Signatur:

```
* Kontaktiere mich:
[![](https://tchncs.de/ico/dsp.png)](https://pod.tchncs.de/u/technics) - [![](https://tchncs.de/ico/tg.jpe)](https://telegram.me/Erdenfreund) - [![](https://tchncs.de/ico/tox.png)](https://toxme.se/u/technics)
```

**Comment by verymilan** [comment]
Leider keine Veränderung mit 62dcced

**Comment by rbeer** [comment]
Auch hier, das Signaturfeld ist einfach komplett ueberholungsbeduerftig.

**Comment by dj95** [comment]
cleanup/inactivity
