### ISSUE TITLE
nestet lists werden als ```code``` dargestellt

### ISSUE THREAD

**Issue by verymilan** [Linux-statt-Windows/nodebb-theme-persona#13]
```
<ul>
    <li>One</li>
    <li>Two</li>
    <li>Three
        <ul>
            <li>Nested One</li>
            <li>Nested Two</li>
        </ul>
    </li>
</ul>
```

wird zu:

```
Two
Three

        Nested One
        Nested Two
```

**Comment by rbeer** [comment]
HTML sollte eigentlich gar nicht funktionieren. oO

**Comment by verymilan** [comment]
Doch, sofern nicht anderes eingestellt, unterstützt Markdown bestimmte HTML Befehle.  `<sub><sub>test</sub>lala</sub>la</sub>` <sub><sub>test</sub>lala</sub>la</sub> zB wurde aus diaspora\* geworfen^^
Für jemanden, der HTML beherrscht und zu faul ist, sich mit Markdown auseinander zu setzen, natürlich vorteilhaft...
![bildschirmfoto vom 2015-11-12 10-06-52](https://cloud.githubusercontent.com/assets/10698140/11114472/4447ff2a-8925-11e5-8885-4bdb78350d78.png)

**Comment by rbeer** [comment]
https://daringfireball.net/projects/markdown/syntax
Stimmt. Wenn nicht in markdown selbst, dann einfach inline HTML. Na gut, mal sehen.

**Comment by dj95** [comment]
cleanup/inactivity
