### ISSUE TITLE
Firefox stellt keine Bilder dar

### ISSUE THREAD

**Issue by rbeer** [Linux-statt-Windows/nodebb-theme-persona#5]
Bei der Darstellung von Bildern in Firefox 41.0.2 lädt die Seite anscheinend neu und versucht iwas zu laden, wobei das Bild nicht mehr dargestellt wird.

![uploads/1193b5e1-489e-41c0-ac5a-8c8e606b1ca9/ff-bilder.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1193b5e1-489e-41c0-ac5a-8c8e606b1ca9%2Fff-bilder.png)

Wenn man die Seite neu lädt, flackert das Bild kurz auf und verschwindet dann wieder.

**Comment by dj95** [comment]
Durch ein anderes Plugin verursacht
